### ISSUE TITLE
Model?

### ISSUE THREAD

**Issue by mnuriyumusak** [koksalkapucuoglu/TomatoLeafDisease#1]
Merhana, öncelikle çalışmanızı tebrik ederim. Bence çok güzel sonuçlar elde etmişsiniz. Repo'da final modeli göremedim. Acaba final model elinizde mevcut mu? Mevcut ise paylaşabilir misiniz? Denemek isterim de gerçekten merak ettim çünkü sahada nasıl performans sergiliyor diye?

**Comment by koksalkapucuoglu** [comment]
Merhaba, teşekkür ederim. Final modelini colab üzerinde tutuyorum. Mail adresini paylaşabilirsen, ekliyeyim.
